# Generated by Django 4.2.9 on 2024-05-23 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_remove_budget_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='name',
        ),
    ]
