# Stage 2: Build Django backend with Elasticsearch
FROM python:3.9-slim

WORKDIR /app/backend


RUN pip install --upgrade pip


# Copy the Django requirements file
COPY requirements.txt ./

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt
RUN python -m pip install Pillow
# Copy the Django project code
COPY . .

# Expose the Django server port
EXPOSE 8000

# Run Django migrations and start the server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
